version: "3.9"
services:
  postgres:
    image: "postgres:15"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "${POSTGRES_PORT}:5432"
  mongo:
    image: "mongo"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DATABASE}"
    ports:
      - "${MONGO_PORT}:27017" 
  redis:
    image: "redis:7"
    ports:
      - "6379:6379"